document.write( '<footer class=\"footer\">\n' );
document.write( '        <div class=\"container\">\n' );
document.write( '            <a href=\"#Z\" id=\"AZ\" title=\"下方功能區塊\" accesskey=\"Z\">:::</a>\n' );
document.write( '            <ul class=\"text-gp\">\n' );
document.write( '                <li>\n' );
document.write( '                    <a href=\"information.html\"><i class=\"fas fa-file-alt\"></i>政府網站資料開放宣告</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li>\n' );
document.write( '                    <a href=\"private.html\"><i class=\"fas fa-file-alt\"></i>隱私權保護政策</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li>\n' );
document.write( '                    <a href=\"security.html\"><i class=\"fas fa-file-alt\"></i>網站安全政策</a>\n' );
document.write( '                </li>\n' );
document.write( '            </ul>\n' );
document.write( '            <div class=\"contact\">\n' );
document.write( '                <a href=\"https://gic.wra.gov.tw/WRA_jsmap/API/mapPainterApi.aspx?id=14\">\n' );
document.write( '                    <i class=\"fas fa-map-marker-alt\"></i>臺中辦公區\n' );
document.write( '                </a>\n' );
document.write( '                <p>電話：(04)2250-1250．(04)2250-1499．傳真：(04)2250-1628．40873臺中市南屯區黎明路2段501號\n' );
document.write( '                </p>\n' );
document.write( '                <a href=\"https://gic.wra.gov.tw/WRA_jsmap/API/mapPainterApi.aspx?id=4\">\n' );
document.write( '                    <i class=\"fas fa-map-marker-alt\"></i>臺北辦公區\n' );
document.write( '                </a>\n' );
document.write( '                <p>電話：(02)3707-3000．(0800)212-239．傳真：(02)3707-3134．10651臺北市大安區信義路3段41-3號9-12樓\n' );
document.write( '                </p>\n' );
document.write( '                <a href=\"https://gic.wra.gov.tw/WRA_jsmap/API/mapPainterApi.aspx?id=15\">\n' );
document.write( '                    <i class=\"fas fa-map-marker-alt\"></i>新店辦公室\n' );
document.write( '                </a>\n' );
document.write( '                <p>電話：(02)8941-5026．23159新北市新店區安和路三段76號</p>\n' );
document.write( '            </div>\n' );
document.write( '            <div class=\"notice\">\n' );
document.write( '                <div class=\"text-gp\">\n' );
document.write( '                    <p>上班時間 彈性上班時間：08:00~09:00, 17:00~18:00﹔核心上班時間：09:00~12:30, 13:30~17:00</p>\n' );
document.write( '                    <p>請使用IE第10版以上、Chrome、FireFox、Edge、Safari瀏覽器瀏覽．最後更新：2020/09/09</p>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"pic\">\n' );
document.write( '                    <a href=\"https://www.handicap-free.nat.gov.tw/Applications/Detail?category=20191015080446\"><img\n' );
document.write( '                            src=\"img/aa2.png\" alt=\"通過AA檢測等級無障礙網頁檢測\"></a>\n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '    </footer>\n' );
document.write( '\n' );
document.write( '    <a href=\"#top\">\n' );
document.write( '        <div class=\"back-top\">▲</div>\n' );
document.write( '    </a>' );
