document.write( '<div class=\"minibar\">\n' );
document.write( '        <div class=\"container\">\n' );
document.write( '            <a href=\"#U\" id=\"AU\" title=\"右上方功能區塊\" accesskey=\"U\" tabindex=\"2\">:::</a>\n' );
document.write( '            <div class=\"btn\">\n' );
document.write( '                <ul>\n' );
document.write( '                    <li><a href=\"login.html\">登入</a></li>\n' );
document.write( '                    <li>|</li>\n' );
document.write( '                    <li><a href=\"sign-up.html\">註冊</a></li>\n' );
document.write( '                </ul>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '\n' );
document.write( '    </div>\n' );
document.write( '    <nav class=\"navbar\">\n' );
document.write( '        <div class=\"pc\">\n' );
document.write( '            <div class=\"navbar-L logo\">\n' );
document.write( '                <a href=\"index.html\">\n' );
document.write( '                    <img src=\"img/infoCompetition-logo.png\" alt=\"logo\">\n' );
document.write( '                </a>\n' );
document.write( '            </div>\n' );
document.write( '            <div class=\"navbar-R\">\n' );
document.write( '                <div class=\"nav-function\">\n' );
document.write( '                    <a href=\"index.html\">\n' );
document.write( '                        <h4>競賽主旨</h4>\n' );
document.write( '                    </a>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"nav-function\">\n' );
document.write( '                    <a href=\"competition-news.html\">\n' );
document.write( '                        <h4>最新消息</h4>\n' );
document.write( '                    </a>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"nav-function\">\n' );
document.write( '                    <a href=\"competition-rules.html\">\n' );
document.write( '                        <h4>競賽辦法</h4>\n' );
document.write( '                    </a>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"nav-function\">\n' );
document.write( '                    <a href=\"competition-judges.html\">\n' );
document.write( '                        <h4>評審委員</h4>\n' );
document.write( '                    </a>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"nav-function\">\n' );
document.write( '                    <a href=\"competition-document.html\">\n' );
document.write( '                        <h4>相關文件</h4>\n' );
document.write( '                    </a>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"nav-function\">\n' );
document.write( '                    <a href=\"competition-notice.html\">\n' );
document.write( '                        <h4>注意事項</h4>\n' );
document.write( '                    </a>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"nav-function\">\n' );
document.write( '                    <a href=\"competition-upload.html\">\n' );
document.write( '                        <h4>資料上傳</h4>\n' );
document.write( '                    </a>\n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"mobile\">\n' );
document.write( '            <div class=\"menu\">\n' );
document.write( '                <div class=\"fas fa-bars\">\n' );
document.write( '                </div>\n' );
document.write( '                <ul class=\"nav navbar-nav\">\n' );
document.write( '                    <li class=\"nav-item dropdown\">\n' );
document.write( '                        <a class=\"nav-link dropdown-toggle\" href=\"javascript:void(0);\" data-toggle=\"dropdown\"\n' );
document.write( '                            aria-haspopup=\"true\" aria-expanded=\"false\">\n' );
document.write( '                            資料展示\n' );
document.write( '                        </a>\n' );
document.write( '                        <div class=\"dropdown-menu shadow-lg\">\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"display-flood.html\">\n' );
document.write( '                                <h4>都市淹水感知器</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"display-river.html\">\n' );
document.write( '                                <h4>河川水位站</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                        </div>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li class=\"nav-item dropdown\">\n' );
document.write( '                        <a class=\"nav-link dropdown-toggle\" href=\"javascript:void(0);\" data-toggle=\"dropdown\"\n' );
document.write( '                            aria-haspopup=\"true\" aria-expanded=\"false\">\n' );
document.write( '                            開發指引\n' );
document.write( '                        </a>\n' );
document.write( '                        <div class=\"dropdown-menu shadow-lg\">\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"theme.html\">\n' );
document.write( '                                <h4>資料主題</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"api-explain.html\">\n' );
document.write( '                                <h4>線上API說明</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"example-code.html\">\n' );
document.write( '                                <h4>範例程式碼</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"data-explain.html\">\n' );
document.write( '                                <h4>資料使用說明</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"data-statistics.html\">\n' );
document.write( '                                <h4>資料使用統計</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                        </div>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li class=\"nav-item dropdown\">\n' );
document.write( '                        <a class=\"nav-link dropdown-toggle\" href=\"javascript:void(0);\" data-toggle=\"dropdown\"\n' );
document.write( '                            aria-haspopup=\"true\" aria-expanded=\"false\">\n' );
document.write( '                            分享專區\n' );
document.write( '                        </a>\n' );
document.write( '                        <div class=\"dropdown-menu shadow-lg\">\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"example-all.html\">\n' );
document.write( '                                <h4>相關連結</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"resources-share.html\">\n' );
document.write( '                                <h4>資源分享</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                        </div>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li class=\"nav-item dropdown\">\n' );
document.write( '                        <a class=\"nav-link dropdown-toggle\" href=\"javascript:void(0);\" role=\"button\"\n' );
document.write( '                            data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n' );
document.write( '                            作業規範\n' );
document.write( '                        </a>\n' );
document.write( '                        <div class=\"dropdown-menu shadow-lg\">\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"rules.html\">\n' );
document.write( '                                <h4>作業規範</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"rules-example.html\">\n' );
document.write( '                                <h4>參考典範指引</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"rules-data.html\">\n' );
document.write( '                                <h4>資料交換標準</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"rules-domain.html\">\n' );
document.write( '                                <h4>領域資料標準</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                        </div>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li class=\"nav-item dropdown\">\n' );
document.write( '                        <a href=\"science-classroom.html\">\n' );
document.write( '                            科普小教室\n' );
document.write( '                        </a>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li class=\"nav-item dropdown\">\n' );
document.write( '                        <a class=\"nav-link dropdown-toggle\" href=\"javascript:void(0);\" role=\"button\"\n' );
document.write( '                            data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n' );
document.write( '                            支援服務\n' );
document.write( '                        </a>\n' );
document.write( '                        <div class=\"dropdown-menu shadow-lg\">\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"opinion.html\">\n' );
document.write( '                                <h4>意見反映</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"FAQ.html\">\n' );
document.write( '                                <h4>FAQ</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                        </div>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li class=\"nav-item dropdown\">\n' );
document.write( '                        <a class=\"nav-link dropdown-toggle\" href=\"javascript:void(0);\" role=\"button\"\n' );
document.write( '                            data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n' );
document.write( '                            會員專區\n' );
document.write( '                        </a>\n' );
document.write( '                        <div class=\"dropdown-menu shadow-lg\">\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"member-data.html\">\n' );
document.write( '                                <h4>會員資料修改</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"api-attestation.html\">\n' );
document.write( '                                <h4>API認證資訊</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                        </div>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li><a href=\"webmap.html\">網站導覽</a></li>\n' );
document.write( '                    <li><a href=\"line.html\">交談機器人</a></li>\n' );
document.write( '                    <li><a href=\"login.html\">登入</a></li>\n' );
document.write( '                    <li><a href=\"sign-up.html\">註冊</a></li>\n' );
document.write( '                </ul>\n' );
document.write( '            </div>\n' );
document.write( '            <div class=\"logo\">\n' );
document.write( '                <a href=\"index.html\">\n' );
document.write( '                    <img src=\"img/logo.jpg\" alt=\"logo\">\n' );
document.write( '                </a>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '    </nav>' );
